import type { ParticleParams } from '../particles/presets'

export function exportVueComponent(presetId: string, params: ParticleParams): string {
  const hasLines = params.linesEnabled
  const hasMouse = params.mouseMode !== 'none'
  const hasClick = params.mouseClick

  const emitterConfig = buildSerializableConfig(presetId, params)

  return `<template>
  <canvas ref="canvasRef" :width="width" :height="height" @mousemove="onMouseMove" @mouseleave="onMouseLeave"${hasClick ? ' @click="onClick"' : ''} />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import * as PIXI from 'pixi.js'
import { Emitter } from '@pixi/particle-emitter'

// ─── Config generated by Particle Generator ───────────────────────────────────
const TEXTURE_URL = 'YOUR_TEXTURE.png' // replace with your texture path
const WIDTH = 512
const HEIGHT = 512
const EMITTER_CONFIG = ${JSON.stringify(emitterConfig, null, 2)}
${hasLines ? `
// Lines
const LINE_DISTANCE = ${params.lineDistance ?? 100}
const LINE_COLOR = 0x${params.lineColor ?? 'ffffff'}
const LINE_OPACITY = ${params.lineOpacity ?? 0.4}
const LINE_WIDTH = ${params.lineWidth ?? 1}` : ''}
${hasMouse ? `
// Mouse
const MOUSE_MODE = '${params.mouseMode}' // 'repulse' | 'attract'
const MOUSE_RADIUS = ${params.mouseRadius ?? 120}
const MOUSE_STRENGTH = ${params.mouseStrength ?? 60}` : ''}
// ──────────────────────────────────────────────────────────────────────────────

const canvasRef = ref<HTMLCanvasElement>()
const width = WIDTH
const height = HEIGHT
${hasMouse ? `const mouse = ref({ x: -9999, y: -9999 })` : ''}

let app: PIXI.Application
let emitter: Emitter
let container: PIXI.Container
${hasLines ? 'let lines: PIXI.Graphics' : ''}
let lastTime = 0

onMounted(() => {
  app = new PIXI.Application({
    view: canvasRef.value!,
    width: WIDTH,
    height: HEIGHT,
    backgroundAlpha: 0,
    antialias: true,
  })

  container = new PIXI.Container()
  container.x = WIDTH / 2 + ${params.emitX ?? 0}
  container.y = HEIGHT / 2 + ${params.emitY ?? 0}
  app.stage.addChild(container)
${hasLines ? `
  lines = new PIXI.Graphics()
  app.stage.addChildAt(lines, 0)` : ''}

  const texture = PIXI.Texture.from(TEXTURE_URL)
  const config = {
    ...EMITTER_CONFIG,
    behaviors: EMITTER_CONFIG.behaviors.map((b: any) =>
      b.type === 'textureSingle' ? { type: 'textureSingle', config: { texture } } : b
    ),
  }

  emitter = new Emitter(container, config)
  emitter.emit = true
  lastTime = performance.now()

  app.ticker.add(() => {
    const now = performance.now()
    const dt = (now - lastTime) / 1000
    lastTime = now
    emitter.update(dt)
${hasMouse ? `
    // Mouse interaction
    const mx = mouse.value.x - container.x
    const my = mouse.value.y - container.y
    container.children.forEach((sprite: any) => {
      const dx = sprite.x - mx
      const dy = sprite.y - my
      const dist = Math.sqrt(dx * dx + dy * dy)
      if (dist < MOUSE_RADIUS && dist > 0) {
        const force = ((MOUSE_RADIUS - dist) / MOUSE_RADIUS) * MOUSE_STRENGTH * dt
        const dir = MOUSE_MODE === 'repulse' ? 1 : -1
        sprite.x += (dx / dist) * force * dir
        sprite.y += (dy / dist) * force * dir
      }
    })` : ''}
${hasLines ? `
    // Line connections
    lines.clear()
    const sprites = container.children
    for (let i = 0; i < sprites.length; i++) {
      for (let j = i + 1; j < sprites.length; j++) {
        const a = sprites[i] as PIXI.Sprite
        const b = sprites[j] as PIXI.Sprite
        const dx = (container.x + a.x) - (container.x + b.x)
        const dy = (container.y + a.y) - (container.y + b.y)
        const dist = Math.sqrt(dx * dx + dy * dy)
        if (dist < LINE_DISTANCE) {
          const alpha = (1 - dist / LINE_DISTANCE) * LINE_OPACITY
          lines.lineStyle(LINE_WIDTH, LINE_COLOR, alpha)
          lines.moveTo(container.x + a.x, container.y + a.y)
          lines.lineTo(container.x + b.x, container.y + b.y)
        }
      }
    }` : ''}
  })
})

onUnmounted(() => {
  emitter?.destroy()
  app?.destroy(false)
})
${hasMouse ? `
function onMouseMove(e: MouseEvent) {
  const rect = canvasRef.value!.getBoundingClientRect()
  mouse.value = {
    x: (e.clientX - rect.left) * (WIDTH / rect.width),
    y: (e.clientY - rect.top) * (HEIGHT / rect.height),
  }
}

function onMouseLeave() {
  mouse.value = { x: -9999, y: -9999 }
}` : `
function onMouseMove(_e: MouseEvent) {}
function onMouseLeave() {}`}
${hasClick ? `
function onClick(e: MouseEvent) {
  const rect = canvasRef.value!.getBoundingClientRect()
  const cx = (e.clientX - rect.left) * (WIDTH / rect.width)
  const cy = (e.clientY - rect.top) * (HEIGHT / rect.height)
  const burstContainer = new PIXI.Container()
  burstContainer.x = cx
  burstContainer.y = cy
  app.stage.addChild(burstContainer)
  const texture = PIXI.Texture.from(TEXTURE_URL)
  const burst = new Emitter(burstContainer, {
    lifetime: { min: 0.2, max: 0.5 },
    frequency: 0.001,
    emitterLifetime: 0.05,
    maxParticles: 15,
    addAtBack: false,
    pos: { x: 0, y: 0 },
    behaviors: [
      { type: 'textureSingle', config: { texture } },
      { type: 'alpha', config: { alpha: { list: [{ value: 1, time: 0 }, { value: 0, time: 1 }] } } },
      { type: 'scale', config: { scale: { list: [{ value: 0.7, time: 0 }, { value: 0, time: 1 }] }, minMult: 0.5 } },
      { type: 'moveSpeed', config: { speed: { list: [{ value: 180, time: 0 }, { value: 20, time: 1 }] }, minMult: 0.5 } },
      { type: 'rotationStatic', config: { min: 0, max: 360 } },
      { type: 'spawnShape', config: { type: 'torus', data: { x: 0, y: 0, radius: 4, innerRadius: 0, affectRotation: false } } },
    ],
  })
  burst.emit = true
  setTimeout(() => { burst.destroy(); app.stage.removeChild(burstContainer) }, 1000)
}` : ''}
</script>
`
}

function buildSerializableConfig(presetId: string, params: ParticleParams) {
  const s = params.speed, l = params.lifetime, sz = params.size, n = params.count, sp = params.spread
  const sizeEnd = params.sizeEnd ?? 0.2
  const aStart = params.alphaStart ?? 1
  const aEnd = params.alphaEnd ?? 0
  const emitR = params.emitRadius ?? 8

  const behaviors: object[] = [
    { type: 'textureSingle', config: { texture: '__TEXTURE__' } },
    { type: 'alpha', config: { alpha: { list: [{ value: aStart, time: 0 }, { value: aEnd, time: 1 }] } } },
    { type: 'scale', config: { scale: { list: [{ value: sz, time: 0 }, { value: sizeEnd, time: 1 }] }, minMult: 0.5 } },
  ]

  if ((params.tintStart ?? 'ffffff') !== 'ffffff' || (params.tintEnd ?? 'ffffff') !== 'ffffff') {
    behaviors.push({ type: 'color', config: { color: { list: [{ value: params.tintStart ?? 'ffffff', time: 0 }, { value: params.tintEnd ?? 'ffffff', time: 1 }] } } })
  }
  if ((params.blendMode ?? 'normal') !== 'normal') {
    behaviors.push({ type: 'blendMode', config: { blendMode: params.blendMode } })
  }
  if ((params.spinSpeed ?? 0) !== 0) {
    const spd = params.spinSpeed!
    behaviors.push({ type: 'rotation', config: { minSpeed: spd, maxSpeed: spd, minStart: 0, maxStart: 360, accel: 0 } })
  }
  if ((params.gravity ?? 0) !== 0) {
    const gy = (params.gravity!) * 600
    behaviors.push({ type: 'moveAcceleration', config: { accel: { x: 0, y: gy }, maxSpeed: 800, rotate: true } })
  }

  const spawnShape = { type: 'spawnShape', config: { type: 'torus', data: { x: 0, y: 0, radius: emitR, innerRadius: 0, affectRotation: false } } }

  const presetBehaviors: Record<string, object[]> = {
    burst:    [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*300, time: 0 }, { value: s*60, time: 1 }] }, minMult: 0.5 } }, { type: 'rotationStatic', config: { min: 0, max: 360 } }, spawnShape],
    sparkler: [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*280, time: 0 }, { value: s*10, time: 1 }] }, minMult: 0.3 } }, { type: 'rotationStatic', config: { min: 0, max: 360 } }, spawnShape],
    floatup:  [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*80, time: 0 }, { value: s*20, time: 1 }] }, minMult: 0.5 } }, { type: 'rotationStatic', config: { min: 250 - sp*30, max: 290 + sp*30 } }, spawnShape],
    rain:     [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*200, time: 0 }, { value: s*180, time: 1 }] }, minMult: 0.8 } }, { type: 'rotationStatic', config: { min: 80 - sp*15, max: 100 + sp*15 } }, spawnShape],
    fountain: [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*380, time: 0 }, { value: s*80, time: 1 }] }, minMult: 0.5 } }, { type: 'rotationStatic', config: { min: 230 - sp*60, max: 310 + sp*60 } }, spawnShape],
    orbit:    [{ type: 'moveSpeed', config: { speed: { list: [{ value: s*30, time: 0 }, { value: s*15, time: 1 }] }, minMult: 0.8 } }, { type: 'spawnShape', config: { type: 'torus', data: { x: 0, y: 0, radius: Math.max(20, emitR*2), innerRadius: Math.max(16, emitR*1.6), affectRotation: true } } }],
  }

  const isOneShot = presetId === 'burst'
  const freqMap: Record<string, number> = {
    burst: 0.001, sparkler: 0.015 / (n/60), floatup: 0.08 / (n/25),
    rain: 0.04 / (n/50), fountain: 0.04 / (n/35), orbit: 0.12 / (n/20),
  }
  const lifetimeMap: Record<string, { min: number; max: number }> = {
    burst: { min: l*0.6, max: l }, sparkler: { min: l*0.3, max: l },
    floatup: { min: l*0.7, max: l }, rain: { min: l*0.8, max: l },
    fountain: { min: l*0.7, max: l }, orbit: { min: l*0.9, max: l },
  }

  return {
    lifetime: lifetimeMap[presetId] ?? { min: l*0.6, max: l },
    frequency: freqMap[presetId] ?? 0.04,
    emitterLifetime: isOneShot ? 0.1 : -1,
    maxParticles: n,
    addAtBack: false,
    pos: { x: 0, y: 0 },
    behaviors: [...behaviors, ...(presetBehaviors[presetId] ?? [])],
  }
}
